spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: welber
    password: welber
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    repair-before-migration: true
    locations: classpath:db/migration/
server:
  port: 8050