services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: welber
      POSTGRES_PASSWORD: welber
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: ms_mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword123
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-express:
    image: mongo-express:1.0.2
    container_name: ms_mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=securepassword123
      - ME_CONFIG_MONGODB_SERVER=ms_mongo_db
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=expresspassword456
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 8081:8081
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080 # User Interface
      - 1025:1025 # SMTP server
    networks:
      - microservices-net

  config-server:
    container_name: config-server
    image: config-server
    build:
      context: ./services/config-server #Path to directory of config-server service
      dockerfile: Dockerfile
    ports:
      - 8889:8888
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices-net
    restart: unless-stopped

  customer:
    container_name: customer
    build:
      context: ./services/customer  # Path to directory of customer service
      dockerfile: Dockerfile
    image: customer
    networks:
      - microservices-net
    restart: unless-stopped

  discovery:
    container_name: discovery
    image: discovery
    build:
      context: ./services/discovery  #Path to directory of discovery service
      dockerfile: Dockerfile
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo_data:
    name: mongo_data