spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  banner:
    location: classpath:banner.txt
server:
  port: 8888
