name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Config Server Docker image
      run: docker build . --file services/config-server/Dockerfile --tag config-server:$(date +%s)
    - name: Build the Product Docker image
      run: docker build . --file services/product/Dockerfile --tag product:$(date +%s)
    - name: Build the Customer Docker image
      run: docker build . --file services/customer/Dockerfile --tag customer:$(date +%s)
    - name: Build the Discovery Docker image
      run: docker build . --file services/discovery/Dockerfile --tag discovery:$(date +%s)
